### ISSUE TITLE
Can this be hosten through github pages

### ISSUE THREAD

**Issue by psteinb** [isse-augsburg/decision-tree-learning-ecml#1]
Thanks for sharing this wonderful tool.

Just dreaming out loud: could this wonderful tool be hosted publically somewhere? Or is it already available somewhere?

**Comment by psteinb** [comment]
never mind, I totally overlooked:
https://ml.isse.de/dt/

**Comment by miriamelia** [comment]
@psteinb thanks for your feedback, enjoy the tool ! :D 
and more feedack is always welcome!
